use_frameworks!

platform :ios, '9.0'

target 'SmilyRate_Example' do
  pod 'SmilyRate', :path => '../'

  target 'SmilyRate_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 9.0.0'
    pod 'SnapKit'
  end
end
